[2018-08-20 23:06:32,194] ERROR in app: Exception on /player [GET]
Traceback (most recent call last):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 259, in decorated_view
    elif not current_user.is_authenticated:
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 355, in _load_user
    return self._load_from_request(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 412, in _load_from_request
    user = self.request_callback(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 79, in request_loader
    if not users.username_check(username):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 49, in username_check
    return True if uid[:6] in [x[:6] for x in self.user_data.keys()] else False # TODO : stop duct taping
TypeError: 'NoneType' object is not subscriptable
192.168.1.6 - - [2018-08-20 23:06:32] "GET /player HTTP/1.0" 500 431 0.007946
192.168.1.6 - - [2018-08-20 23:06:38] "GET /login/%0F7/:2=< HTTP/1.0" 302 677 0.004968
192.168.1.6 - - [2018-08-20 23:06:38] "GET /player HTTP/1.0" 200 9185 0.060404
192.168.1.6 - - [2018-08-20 23:06:38] "GET /picture/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 9382 0.006749
192.168.1.6 - - [2018-08-20 23:06:41] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 3511934 2.513200
192.168.1.6 - - [2018-08-20 23:06:43] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 3511934 0.259962
192.168.1.6 - - [2018-08-20 23:07:30] "GET /charge HTTP/1.0" 200 1330 0.005677
192.168.1.6 - - [2018-08-20 23:07:46] "GET /login/%0F7/:2=< HTTP/1.0" 302 678 0.003553
192.168.1.6 - - [2018-08-20 23:07:46] "GET /player HTTP/1.0" 200 9185 0.002640
192.168.1.6 - - [2018-08-20 23:07:47] "GET /picture/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 9382 0.003154
192.168.1.6 - - [2018-08-20 23:07:47] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 254291 0.021020
192.168.1.6 - - [2018-08-20 23:07:49] "GET /player HTTP/1.0" 200 9185 0.003152
192.168.1.6 - - [2018-08-20 23:07:50] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 237907 0.012194
192.168.1.6 - - [2018-08-20 23:08:22] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 3511934 0.773997
192.168.1.6 - - [2018-08-20 23:21:05] "POST /charge HTTP/1.0" 302 418 0.009400
192.168.1.6 - - [2018-08-20 23:21:05] "GET /player HTTP/1.0" 200 9185 0.000922
192.168.1.6 - - [2018-08-20 23:21:24] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 1753427 19.120140
192.168.1.6 - - [2018-08-20 23:21:50] "GET /player HTTP/1.0" 200 9185 0.001676
192.168.1.6 - - [2018-08-20 23:22:09] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 2531667 19.385438
192.168.1.6 - - [2018-08-20 23:22:11] "GET /player HTTP/1.0" 200 9185 0.003175
192.168.1.6 - - [2018-08-20 23:22:15] "GET /player HTTP/1.0" 200 9185 0.003195
192.168.1.6 - - [2018-08-20 23:22:15] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 1753427 4.267253
192.168.1.6 - - [2018-08-20 23:22:34] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 1548627 18.391830
192.168.1.6 - - [2018-08-20 23:22:59] "GET /player HTTP/1.0" 200 9778 0.102575
192.168.1.6 - - [2018-08-20 23:23:05] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 1614163 5.185903
192.168.1.6 - - [2018-08-20 23:23:05] "GET /picture/Full%20Metal%20Panic!%20Fumoffu%20ending%20full%20w%20lyrics HTTP/1.0" 200 16769 0.003360
192.168.1.6 - - [2018-08-20 23:23:05] "GET /player/Full%20Metal%20Panic!%20Fumoffu%20ending%20full%20w%20lyrics HTTP/1.0" 200 4416808 0.294211
192.168.1.6 - - [2018-08-20 23:27:13] "GET /charge HTTP/1.0" 200 1330 0.002568
192.168.1.6 - - [2018-08-20 23:27:15] "POST /charge HTTP/1.0" 302 418 0.005706
192.168.1.6 - - [2018-08-20 23:27:15] "GET /player HTTP/1.0" 200 9778 0.001276
192.168.1.6 - - [2018-08-20 23:27:19] "GET /player/Shoujo%20Shuumatsu%20Ryokou%20ED HTTP/1.0" 200 3511934 3.595712
192.168.1.6 - - [2018-08-20 23:27:49] "GET /player/Full%20Metal%20Panic!%20Fumoffu%20ending%20full%20w%20lyrics HTTP/1.0" 200 4416808 1.062588
192.168.1.6 - - [2018-08-20 23:30:29] "GET /player HTTP/1.0" 200 10452 0.153397
[2018-08-20 23:43:01,837] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 259, in decorated_view
    elif not current_user.is_authenticated:
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 355, in _load_user
    return self._load_from_request(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 412, in _load_from_request
    user = self.request_callback(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 79, in request_loader
    if not users.username_check(username):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 49, in username_check
    return True if uid[:6] in [x[:6] for x in self.user_data.keys()] else False # TODO : stop duct taping
TypeError: 'NoneType' object is not subscriptable
192.168.1.6 - - [2018-08-20 23:43:01] "GET / HTTP/1.0" 500 431 0.004127
[2018-08-20 23:52:03,717] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 259, in decorated_view
    elif not current_user.is_authenticated:
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 355, in _load_user
    return self._load_from_request(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/env/lib/python3.6/site-packages/flask_login/login_manager.py", line 412, in _load_from_request
    user = self.request_callback(request)
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 79, in request_loader
    if not users.username_check(username):
  File "/home/ruwevcedt/OriginalSinMusic/redtube/core/_login.py", line 49, in username_check
    return True if uid[:6] in [x[:6] for x in self.user_data.keys()] else False # TODO : stop duct taping
TypeError: 'NoneType' object is not subscriptable
